---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontend
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
    - hosts:
      - "momo-store-std-022-024.ru"
      secretName: momo-certbot-tls
  rules:
    - host: "momo-store-std-022-024.ru"
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: frontend-service
              port:
                number: 80