---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf-configmap
data:
  nginx.conf: |-
    worker_processes  5;
    events {
      worker_connections  1024;
    }
    http {
      server {
        listen 80;

        location / {
          root /var/www-data;
          index index.html;
          try_files $uri $uri/ /index.html;


        }

        location ~ ^/(categories|products|auth|metrics|orders)/ {
              proxy_pass http://backend:8081;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   /usr/share/nginx/html;
        }

      }
    }

   
