apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Chart.Name }}-{{ .Values.imagePullSecrets.name }}"
data:
  {{ .Values.imagePullSecrets.key }}: {{ .Values.imagePullSecrets.value }}
type: {{ .Values.imagePullSecrets.type }} 
